# Backend configuration
backend:
  name: free
  image: docker.io/rkaeffer/codelab-gitops-backend:1.0.0
  containerPort: 8080
  host: julien-archambault-kcl.codelab.cloud-sp.eu
  service:
    port: 443