apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.backend.name }}
spec:
  tls:
  - hosts:
    - {{ .Values.backend.host }}
  rules:
    - host: {{ .Values.backend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-{{ .Values.backend.name }}
                port:
                  number: {{ .Values.backend.service.port }}