apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
spec:
  tls:
  - hosts:
    - rkaeffer-kcl-frontend.codelab.cloud-sp.eu
  rules:
    - host: rkaeffer-kcl-frontend.codelab.cloud-sp.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 443